RUN python:3.9.12

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrate pip && pip install -r requirements.txt
COPY bot.py bot.py


WORKDIR /app/datasets
COPY bgg_boardgames_top_2000.feather bgg_boardgames_top_2000.feather
COPY bgg_ratings_top_2000.feather bgg_ratings_top_2000.feather

WORKDIR /app/models
COPY als_model.npz als_model.npz

WORKDIR /app/notebooks
COPY board_game_recommender_notebook.ipynb board_game_recommender_notebook.ipynb

WORKDIR /app/database
COPY user_data.sql user_data.sql

WORKDIR /app/


ENTRYPOINT ["python3", "bot.py"]


